- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yaml
- name: golong installation
  ansible.builtin.import_role:
    name: common
    tasks_from: go.yaml
- name: system app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd.yaml