- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yaml
- name: nodejs installation
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs.yaml
- name: mongo app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: mongodb-setup
- name: system app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd.yaml
# - name: deployment
#   ansible.builtin.import_role:
#     name: common
#     task_from: deployment.yaml