- name: adding user
  ansible.builtin.user:
    name: roboshop
- name: romoving app directory
  ansible.builtin.file:
    path: /app
    state: absent
- name: creating app directory
  ansible.builtin.file:
    path: /app
    state: directory
- name: download artifact from nexus
  ansible.builtin.get_url:
    url: "{{NEXUS_URL}}/{{component}}/{{groupid}}/{{component}}/{{app_version}}/{{component}}-{{app_version}}.zip"
    dest: /tmp
- name: unarchive the zip file
  ansible.builtin.unarchive:
    src:  "/tmp/{{component}}-{{app_version}}.zip"
    dest: /app
    remote_src: yes

# - name: download {{component}} from url 
#   ansible.builtin.get_url:
#     url: "https://roboshop-builds.s3.amazonaws.com/{{component}}.zip"
#     dest: "/tmp/{{component}}.zip"
  