- name: adding user
  ansible.builtin.user:
    name: roboshop
- name: romoving app directory
  ansible.builtin.file:
    path: /app
    state: absent
- name: creating app directory
  ansible.builtin.file:
    path: /app
    state: directory
- name: download {{component}} from url 
  ansible.builtin.get_url:
    url: "https://roboshop-builds.s3.amazonaws.com/{{component}}.zip"
    dest: "/tmp/{{component}}.zip"
- name: unarchive the zip file
  ansible.builtin.unarchive:
    src:  "/tmp/{{component}}.zip"
    dest: /app
    remote_src: yes
  