- name: install mysql
  ansible.builtin.package:
    name: mysql
    state: present
- name: check cities data aleady available or not 
  ansible.builtin.shell: mysql -h mysql.infome.website -uroot -pRoboShop@1 -sN -e "select count(*) from information_schema.schemata where schema_name ='cities'"
  register: schema
- name: data load cities
  ansible.builtin.shell: "mysql -h mysql.infome.website -uroot -pRoboShop@1 < /app/schema/shipping.sql"
  when: schema.stdout != "1"
